# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_modification.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(498, 350)
        self.part_selector = QtWidgets.QComboBox(Form)
        self.part_selector.setGeometry(QtCore.QRect(10, 30, 91, 21))
        self.part_selector.setObjectName("part_selector")
        self.part_selector.addItem("")
        self.part_selector.addItem("")
        self.part_selector.addItem("")
        self.manufacturer_input = QtWidgets.QLineEdit(Form)
        self.manufacturer_input.setGeometry(QtCore.QRect(110, 30, 113, 22))
        self.manufacturer_input.setObjectName("manufacturer_input")
        self.km_input = QtWidgets.QLineEdit(Form)
        self.km_input.setGeometry(QtCore.QRect(240, 30, 113, 22))
        self.km_input.setObjectName("km_input")
        self.date_input = QtWidgets.QDateEdit(Form)
        self.date_input.setGeometry(QtCore.QRect(380, 30, 110, 22))
        self.date_input.setObjectName("date_input")
        self.save_button = QtWidgets.QPushButton(Form)
        self.save_button.setGeometry(QtCore.QRect(10, 70, 481, 91))
        self.save_button.setObjectName("save_button")
        self.message_label = QtWidgets.QLabel(Form)
        self.message_label.setGeometry(QtCore.QRect(24, 189, 221, 131))
        self.message_label.setText("")
        self.message_label.setObjectName("message_label")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(30, 10, 55, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(270, 10, 55, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(130, 10, 71, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(410, 10, 55, 20))
        self.label_4.setObjectName("label_4")
        self.view_all_button = QtWidgets.QPushButton(Form)
        self.view_all_button.setGeometry(QtCore.QRect(280, 170, 201, 41))
        self.view_all_button.setObjectName("view_all_button")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.part_selector.setItemText(0, _translate("Form", "Brat"))
        self.part_selector.setItemText(1, _translate("Form", "Filtre"))
        self.part_selector.setItemText(2, _translate("Form", "Discuri frana "))
        self.save_button.setText(_translate("Form", "PushButton"))
        self.label.setText(_translate("Form", "  Piesa "))
        self.label_2.setText(_translate("Form", "Rulajul"))
        self.label_3.setText(_translate("Form", "Producatorul"))
        self.label_4.setText(_translate("Form", "Data "))
        self.view_all_button.setText(_translate("Form", "Vezi toate modificarile"))
