# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(473, 366)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 20, 41, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(20, 50, 51, 16))
        self.label_2.setObjectName("label_2")
        self.email_input = QtWidgets.QLineEdit(Form)
        self.email_input.setGeometry(QtCore.QRect(80, 20, 113, 22))
        self.email_input.setObjectName("email_input")
        self.password_input = QtWidgets.QLineEdit(Form)
        self.password_input.setGeometry(QtCore.QRect(80, 50, 113, 22))
        self.password_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_input.setObjectName("password_input")
        self.register_button = QtWidgets.QPushButton(Form)
        self.register_button.setGeometry(QtCore.QRect(10, 80, 81, 51))
        self.register_button.setObjectName("register_button")
        self.login_button = QtWidgets.QPushButton(Form)
        self.login_button.setGeometry(QtCore.QRect(100, 77, 93, 61))
        self.login_button.setObjectName("login_button")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Email :"))
        self.label_2.setText(_translate("Form", "Parola :"))
        self.register_button.setText(_translate("Form", "Inregistrare"))
        self.login_button.setText(_translate("Form", "Login"))
