# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view_modifications.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(596, 324)
        self.modifications_table = QtWidgets.QTableWidget(Form)
        self.modifications_table.setGeometry(QtCore.QRect(10, 20, 581, 221))
        self.modifications_table.setObjectName("modifications_table")
        self.modifications_table.setColumnCount(4)
        self.modifications_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.modifications_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.modifications_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.modifications_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.modifications_table.setHorizontalHeaderItem(3, item)
        self.close_button = QtWidgets.QPushButton(Form)
        self.close_button.setGeometry(QtCore.QRect(20, 250, 541, 28))
        self.close_button.setObjectName("close_button")
        self.export_button = QtWidgets.QPushButton(Form)
        self.export_button.setGeometry(QtCore.QRect(172, 290, 211, 28))
        self.export_button.setObjectName("export_button")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        item = self.modifications_table.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Piesa"))
        item = self.modifications_table.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Producator"))
        item = self.modifications_table.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Rulaj"))
        item = self.modifications_table.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Data"))
        self.close_button.setText(_translate("Form", "inchide"))
        self.export_button.setText(_translate("Form", "Exportă toate modificările"))
