# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vin_input.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 30, 71, 31))
        self.label.setObjectName("label")
        self.vin_input = QtWidgets.QLineEdit(Form)
        self.vin_input.setGeometry(QtCore.QRect(100, 30, 161, 31))
        self.vin_input.setObjectName("vin_input")
        self.search_button = QtWidgets.QPushButton(Form)
        self.search_button.setGeometry(QtCore.QRect(270, 30, 93, 28))
        self.search_button.setObjectName("search_button")
        self.result_box = QtWidgets.QTextEdit(Form)
        self.result_box.setGeometry(QtCore.QRect(160, 70, 231, 171))
        self.result_box.setObjectName("result_box")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Serie sasiu :lin"))
        self.search_button.setText(_translate("Form", "Cauta"))
